package ch.unartig.sportrait.client.forms;


import javax.swing.*;
import java.awt.*;

/**
 * Created by IntelliJ IDEA.
 * User: alexanderjosef
 * Date: Jul 1, 2008
 * Time: 7:08:04 PM
 * To change this template use File | Settings | File Templates.
 */
public class UnartigClientAppletForm {
    private JPanel unartigClientPanel;
    private JList chooseYourCategoryList;
    private JList chooseYourEventList;

    public void createUIComponents() {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        unartigClientPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setFont(new Font(label1.getFont().getName(), Font.BOLD, 18));
        label1.setText("ZIEL:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        unartigClientPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("(Event und Kategorie fŸr Foto-Upload wŠhlen)");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 4;
        gbc.anchor = GridBagConstraints.WEST;
        unartigClientPanel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Anlass");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        unartigClientPanel.add(label3, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.gridwidth = 4;
        gbc.anchor = GridBagConstraints.WEST;
        unartigClientPanel.add(panel1, gbc);
        final JLabel label4 = new JLabel();
        label4.setFont(new Font(label4.getFont().getName(), Font.BOLD, 18));
        label4.setText("Quelle:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.gridwidth = 4;
        gbc.anchor = GridBagConstraints.WEST;
        unartigClientPanel.add(label4, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        unartigClientPanel.add(panel2, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        unartigClientPanel.add(panel3, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Kategorie");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        unartigClientPanel.add(label5, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setVerticalScrollBarPolicy(22);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        unartigClientPanel.add(scrollPane1, gbc);
        chooseYourCategoryList = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        defaultListModel1.addElement("Category1");
        defaultListModel1.addElement("Category1");
        defaultListModel1.addElement("Category1");
        defaultListModel1.addElement("Category1");
        defaultListModel1.addElement("Category1");
        defaultListModel1.addElement("Category1");
        defaultListModel1.addElement("Category1");
        defaultListModel1.addElement("Category1");
        defaultListModel1.addElement("Category1");
        defaultListModel1.addElement("Category1");
        defaultListModel1.addElement("Category1");
        defaultListModel1.addElement("Category1");
        defaultListModel1.addElement("Long Cagtegoryadsfa");
        chooseYourCategoryList.setModel(defaultListModel1);
        chooseYourCategoryList.setSelectionMode(0);
        scrollPane1.setViewportView(chooseYourCategoryList);
        final JScrollPane scrollPane2 = new JScrollPane();
        scrollPane2.setVerticalScrollBarPolicy(22);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        unartigClientPanel.add(scrollPane2, gbc);
        chooseYourEventList = new JList();
        final DefaultListModel defaultListModel2 = new DefaultListModel();
        defaultListModel2.addElement("Category1");
        defaultListModel2.addElement("Category1");
        defaultListModel2.addElement("Category1");
        defaultListModel2.addElement("Category1");
        defaultListModel2.addElement("Category1");
        defaultListModel2.addElement("Category1");
        defaultListModel2.addElement("Category1");
        defaultListModel2.addElement("Category1");
        defaultListModel2.addElement("Category1");
        defaultListModel2.addElement("Category1");
        defaultListModel2.addElement("Category1");
        defaultListModel2.addElement("Category1");
        defaultListModel2.addElement("Long Cagtegoryadsfa");
        chooseYourEventList.setModel(defaultListModel2);
        chooseYourEventList.setSelectionMode(0);
        scrollPane2.setViewportView(chooseYourEventList);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        unartigClientPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        unartigClientPanel.add(spacer2, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return unartigClientPanel;
    }
}
