package ch.unartig.sportrait.client.forms;

import javax.swing.*;
import java.awt.*;

/**
 * Created by IntelliJ IDEA.
 * User: alexanderjosef
 * Date: Jul 2, 2008
 * Time: 7:46:22 AM
 * To change this template use File | Settings | File Templates.
 */
public class UnartigClientAppletForm {
    public JList chooseYourCategoryList;
    public JList chooseYourEventList;
    public JPanel eventCategoryChooserPanel;


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        eventCategoryChooserPanel = new JPanel();
        eventCategoryChooserPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setFont(new Font(label1.getFont().getName(), Font.BOLD, 18));
        label1.setText("ZIEL:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        eventCategoryChooserPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("(Event und Kategorie fŸr Foto-Upload bestimmen)");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 4;
        gbc.anchor = GridBagConstraints.WEST;
        eventCategoryChooserPanel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Anlass");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        eventCategoryChooserPanel.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setFont(new Font(label4.getFont().getName(), Font.BOLD, 18));
        label4.setText("QUELLE:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.gridwidth = 4;
        gbc.anchor = GridBagConstraints.WEST;
        eventCategoryChooserPanel.add(label4, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setPreferredSize(new Dimension(200, 100));
        scrollPane1.setVerticalScrollBarPolicy(22);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        eventCategoryChooserPanel.add(scrollPane1, gbc);
        chooseYourCategoryList = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        defaultListModel1.addElement("category1");
        defaultListModel1.addElement("asdf");
        defaultListModel1.addElement("asd");
        defaultListModel1.addElement("fasd");
        defaultListModel1.addElement("fasdfasdfas");
        defaultListModel1.addElement("df");
        defaultListModel1.addElement("afsd");
        defaultListModel1.addElement("f");
        chooseYourCategoryList.setModel(defaultListModel1);
        chooseYourCategoryList.setPreferredSize(new Dimension(200, 100));
        chooseYourCategoryList.setRequestFocusEnabled(false);
        chooseYourCategoryList.setSelectionMode(0);
        scrollPane1.setViewportView(chooseYourCategoryList);
        final JScrollPane scrollPane2 = new JScrollPane();
        scrollPane2.setPreferredSize(new Dimension(200, 100));
        scrollPane2.setRequestFocusEnabled(false);
        scrollPane2.setVerticalScrollBarPolicy(22);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        eventCategoryChooserPanel.add(scrollPane2, gbc);
        chooseYourEventList = new JList();
        final DefaultListModel defaultListModel2 = new DefaultListModel();
        defaultListModel2.addElement("event1");
        defaultListModel2.addElement("asdf");
        defaultListModel2.addElement("asdf");
        defaultListModel2.addElement("asdf");
        defaultListModel2.addElement("asd");
        defaultListModel2.addElement("f");
        chooseYourEventList.setModel(defaultListModel2);
        chooseYourEventList.setPreferredSize(new Dimension(200, 100));
        chooseYourEventList.setSelectionMode(0);
        scrollPane2.setViewportView(chooseYourEventList);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        eventCategoryChooserPanel.add(spacer1, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Kategorie");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        eventCategoryChooserPanel.add(label5, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        eventCategoryChooserPanel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        eventCategoryChooserPanel.add(spacer3, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("(Fotos auswŠhlen)");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.gridwidth = 5;
        gbc.anchor = GridBagConstraints.WEST;
        eventCategoryChooserPanel.add(label6, gbc);
        final JSeparator separator1 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.BOTH;
        eventCategoryChooserPanel.add(separator1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return eventCategoryChooserPanel;
    }
}
