/*-*
 *
 * FILENAME  :
 *    $RCSfile$
 *
 *    @author alex$
 *    @since 26.09.2007$
 *
 * Copyright (c) 2006 Alexander Josef,unartig AG; All rights reserved
 *
 * STATUS  :
 *    $Revision$, $State$, $Name$
 *
 *    $Author$, $Locker$
 *    $Date$
 *
 *************************************************
 * $Log$
 ****************************************************************/
package ch.unartig;

import ch.unartig.sportrait.client.JUnartigUploadClientPanel;

import javax.swing.*;
import java.awt.*;

public class TestForm
{
    private JPanel panel1;
    private JList list1;
    private JList list2;


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setBorder(BorderFactory.createTitledBorder(""));
        final JScrollPane scrollPane1 = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(scrollPane1, gbc);
        list1 = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        defaultListModel1.addElement("asdf");
        defaultListModel1.addElement("dsaf");
        defaultListModel1.addElement("asdf");
        defaultListModel1.addElement("asdf");
        defaultListModel1.addElement("asdf");
        defaultListModel1.addElement("asd");
        defaultListModel1.addElement("fasd");
        defaultListModel1.addElement("fasd");
        defaultListModel1.addElement("fasd");
        defaultListModel1.addElement("f");
        defaultListModel1.addElement("asdf");
        defaultListModel1.addElement("asd");
        defaultListModel1.addElement("fas");
        defaultListModel1.addElement("df");
        defaultListModel1.addElement("asdf");
        list1.setModel(defaultListModel1);
        scrollPane1.setViewportView(list1);
        final JLabel label1 = new JLabel();
        label1.setText("Event und Kategorie waehlen:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Event");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Kategorie");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label3, gbc);
        final JScrollPane scrollPane2 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(scrollPane2, gbc);
        list2 = new JList();
        final DefaultListModel defaultListModel2 = new DefaultListModel();
        defaultListModel2.addElement("asdf");
        defaultListModel2.addElement("dsaf");
        defaultListModel2.addElement("asdf");
        defaultListModel2.addElement("asdf");
        defaultListModel2.addElement("asdf");
        defaultListModel2.addElement("asd");
        defaultListModel2.addElement("fasd");
        defaultListModel2.addElement("fasd");
        defaultListModel2.addElement("fasd");
        defaultListModel2.addElement("f");
        defaultListModel2.addElement("asdf");
        defaultListModel2.addElement("asd");
        defaultListModel2.addElement("fas");
        defaultListModel2.addElement("df");
        defaultListModel2.addElement("asdf");
        list2.setModel(defaultListModel2);
        scrollPane2.setViewportView(list2);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return panel1;
    }
}
